SKILL_ALIASES: dict = {
    "javascript": ["javascript", "js", "es6"],
    "typescript": ["typescript", "ts"],
    "python": ["python", "py"],
    "node.js": ["node.js", "nodejs", "node js", "node"],
    "react": ["react", "react.js", "reactjs"],
    "next.js": ["next.js", "nextjs"],
    "vue": ["vue", "vue.js", "vuejs"],
    "angular": ["angular", "angularjs"],
    "postgresql": ["postgresql", "postgres"],
    "mysql": ["mysql"],
    "mongodb": ["mongodb", "mongo"],
    "microsoft sql server": ["microsoft sql server", "mssql", "sql server", "ms sql"],
    "amazon web services": ["amazon web services", "aws"],
    "google cloud platform": ["google cloud platform", "gcp", "google cloud"],
    "microsoft azure": ["microsoft azure", "azure"],
    "kubernetes": ["kubernetes", "k8s"],
    "docker": ["docker", "dockerfile"],
    "machine learning": ["machine learning", "ml"],
    "artificial intelligence": ["artificial intelligence", "ai"],
    "natural language processing": ["natural language processing", "nlp"],
    "power bi": ["power bi", "powerbi", "power-bi"],
    "microsoft fabric": ["microsoft fabric", "fabric", "ms fabric"],
    "dax": ["dax", "data analysis expressions"],
    "tableau": ["tableau"],
    "looker": ["looker", "looker studio"],
    "c#": ["c#", "c sharp", "csharp"],
    "c++": ["c++", "cpp"],
    ".net": [".net", "dotnet", "dot net"],
    "spring boot": ["spring boot", "springboot"],
    "django": ["django"],
    "fastapi": ["fastapi", "fast api"],
    "flask": ["flask"],
    "terraform": ["terraform"],
    "git": ["git", "github", "gitlab", "bitbucket"],
    "kafka": ["kafka", "apache kafka"],
    "spark": ["spark", "apache spark", "pyspark"],
    "snowflake": ["snowflake"],
    "dbt": ["dbt", "data build tool"],
    "airflow": ["airflow", "apache airflow"],
    "power query": ["power query", "m language"],
    "sql": ["sql", "structured query language"],
    "rest api": ["rest api", "restful", "rest"],
    "graphql": ["graphql"],
    "microservices": ["microservices", "micro services"],
    "ci/cd": ["ci/cd", "cicd", "continuous integration", "continuous deployment"],
    "agile": ["agile", "scrum", "kanban"],
    "elasticsearch": ["elasticsearch", "opensearch"],
    "redis": ["redis"],
    "semantic modeling": ["semantic modeling", "semantic model"],
}

SKILL_EQUIVALENTS: dict = {
    "power bi":         [("tableau", 0.45), ("looker", 0.45), ("qlik", 0.45), ("metabase", 0.40)],
    "tableau":          [("power bi", 0.45), ("looker", 0.45)],
    "dax":              [("mdx", 0.45), ("power query", 0.40)],
    "microsoft fabric": [("azure synapse", 0.45), ("databricks", 0.45), ("azure data factory", 0.40)],
    "react":            [("vue", 0.45), ("angular", 0.45)],
    "vue":              [("react", 0.45), ("angular", 0.45)],
    "angular":          [("react", 0.45), ("vue", 0.45)],
    "postgresql":       [("mysql", 0.45), ("oracle", 0.40), ("microsoft sql server", 0.40)],
    "mysql":            [("postgresql", 0.45)],
    "amazon web services": [("microsoft azure", 0.45), ("google cloud platform", 0.45)],
    "microsoft azure":  [("amazon web services", 0.45), ("google cloud platform", 0.45)],
    "kubernetes":       [("docker swarm", 0.45), ("ecs", 0.40)],
    "snowflake":        [("bigquery", 0.45), ("redshift", 0.45)],
    "airflow":          [("prefect", 0.45), ("dagster", 0.45)],
    "kafka":            [("rabbitmq", 0.40), ("kinesis", 0.40)],
    "django":           [("flask", 0.45), ("fastapi", 0.45)],
    "fastapi":          [("flask", 0.45), ("django", 0.40)],
    "terraform":        [("pulumi", 0.45), ("ansible", 0.40)],
    "elasticsearch":    [("opensearch", 0.50), ("solr", 0.40)],
}

DEPTH_SIGNALS: dict = {
    "architected": 5, "designed": 4, "built": 4, "led": 4,
    "established": 4, "pioneered": 5, "spearheaded": 4, "owned": 3,
    "created": 3, "developed": 3, "implemented": 3, "engineered": 4,
    "delivered": 3, "production": 3, "enterprise": 3, "million": 4,
    "scale": 3, "distributed": 4, "real-time": 3, "mentored": 4,
    "trained": 3, "certified": 4, "certification": 4, "senior": 3,
    "principal": 4, "lead": 3, "expert": 3, "years": 3,
    "exposure": -4, "familiar": -3, "basic": -4, "beginner": -5,
    "learning": -3, "coursework": -3, "limited": -4, "assisted": -2,
    "helped": -2, "exploring": -3, "understanding of": -2,
}

EDUCATION_RANK: dict = {
    "high school": 1, "diploma": 2, "associate": 3,
    "bachelor": 4, "b.tech": 4, "b.e": 4, "be": 4,
    "bsc": 4, "b.sc": 4, "undergraduate": 4,
    "master": 5, "m.tech": 5, "msc": 5, "m.sc": 5,
    "mba": 5, "postgraduate": 5,
    "phd": 6, "doctorate": 6, "doctoral": 6,
}
